<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_58e61c07c7f31',
        'title' => 'About Details',
        'fields' => array (
            array (
                'key' => 'field_58e61c3dc73ca',
                'label' => 'Position',
                'name' => 'ad_position',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58e61c4fc73cb',
                'label' => 'Email',
                'name' => 'ad_email',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58e61c73c73cc',
                'label' => 'Phone',
                'name' => 'ad_phone',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'team',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_58e528ed0ea9f',
        'title' => 'Layout Builder',
        'fields' => array (
            array (
                'key' => 'field_58e529040c661',
                'label' => 'Modules',
                'name' => 'layout_modules',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'button_label' => 'Add Row',
                'min' => '',
                'max' => '',
                'layouts' => array (
                    array (
                        'key' => '58e5290e8e20c',
                        'name' => 'intro',
                        'label' => 'Intro',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58ed004005f9b',
                                'label' => 'Display Option',
                                'name' => 'intro_display_option',
                                'type' => 'checkbox',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Title' => 'Title',
                                    'Description' => 'Description',
                                    'View More Link' => 'View More Link',
                                ),
                                'default_value' => array (
                                ),
                                'layout' => 'horizontal',
                                'toggle' => 0,
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_58e529460c662',
                                'label' => 'TItle',
                                'name' => 'into_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ed004005f9b',
                                            'operator' => '==',
                                            'value' => 'Title',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58e5296d0c663',
                                'label' => 'Description',
                                'name' => 'intro_content',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ed004005f9b',
                                            'operator' => '==',
                                            'value' => 'Description',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => 'wpautop',
                            ),
                            array (
                                'key' => 'field_58ecf2676169a',
                                'label' => 'Link',
                                'name' => 'intro_vlink',
                                'type' => 'link_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ed004005f9b',
                                            'operator' => '==',
                                            'value' => 'View More Link',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58e52d06c951b',
                        'name' => 'hero',
                        'label' => 'Hero',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58e52dedc951f',
                                'label' => 'Display Option',
                                'name' => 'display_option',
                                'type' => 'checkbox',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Title' => 'Title',
                                    'Description' => 'Description',
                                    'View More Button' => 'View More Button',
                                ),
                                'default_value' => array (
                                ),
                                'layout' => 'vertical',
                                'toggle' => 0,
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_58e52d11c951c',
                                'label' => 'Title',
                                'name' => 'hero_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58e52dedc951f',
                                            'operator' => '==',
                                            'value' => 'Title',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58e52d4ac951d',
                                'label' => 'Content',
                                'name' => 'hero_content',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58e52dedc951f',
                                            'operator' => '==',
                                            'value' => 'Description',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => 'wpautop',
                            ),
                            array (
                                'key' => 'field_58ecf602b4b3f',
                                'label' => 'View More Link',
                                'name' => 'hero_vlink',
                                'type' => 'link_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58e52dedc951f',
                                            'operator' => '==',
                                            'value' => 'View More Button',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58e531d6b1aad',
                        'name' => 'process',
                        'label' => 'Process',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58ecf42d1534b',
                                'label' => 'Display Option',
                                'name' => 'process_d_setting',
                                'type' => 'checkbox',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Title' => 'Title',
                                    'Description' => 'Description',
                                    'View More LInk' => 'View More LInk',
                                ),
                                'default_value' => array (
                                ),
                                'layout' => 'horizontal',
                                'toggle' => 0,
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_58e531d6b1aaf',
                                'label' => 'Title',
                                'name' => 'process_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ecf42d1534b',
                                            'operator' => '==',
                                            'value' => 'Title',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58e531d6b1ab0',
                                'label' => 'Content',
                                'name' => 'process_content',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ecf42d1534b',
                                            'operator' => '==',
                                            'value' => 'Description',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => 'wpautop',
                            ),
                            array (
                                'key' => 'field_58e5329bb1aba',
                                'label' => 'Process Layout',
                                'name' => 'process_layout',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Simple' => 'Simple',
                                    'Full' => 'Full',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_5909a565becb9',
                                'label' => 'Process Items',
                                'name' => 'process_items',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => '',
                                'max' => '',
                                'layout' => 'row',
                                'button_label' => 'Add Row',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_5909a739becba',
                                        'label' => 'Title',
                                        'name' => 'process_item_title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_5909a823becbb',
                                        'label' => 'Sub TItle',
                                        'name' => 'process_item_stitle',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_5909a845becbc',
                                        'label' => 'Type',
                                        'name' => 'process_item_type',
                                        'type' => 'radio',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array (
                                            'Default Icons' => 'Default Icons',
                                            'Upload Custom Icon' => 'Upload Custom Icon',
                                        ),
                                        'allow_null' => 0,
                                        'other_choice' => 0,
                                        'save_other_choice' => 0,
                                        'default_value' => '',
                                        'layout' => 'horizontal',
                                        'return_format' => 'value',
                                    ),
                                    array (
                                        'key' => 'field_5909a866becbd',
                                        'label' => 'Icon',
                                        'name' => 'process_item_icon',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5909a845becbc',
                                                    'operator' => '==',
                                                    'value' => 'Default Icons',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array (
                                            'Foundation' => 'Foundation',
                                            'Arrowup' => 'Arrowup',
                                            'Navigate' => 'Navigate',
                                            'Activate' => 'Activate',
                                            'Check' => 'Check',
                                        ),
                                        'default_value' => array (
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'ajax' => 0,
                                        'return_format' => 'value',
                                        'placeholder' => '',
                                    ),
                                    array (
                                        'key' => 'field_5909a89ebecbe',
                                        'label' => 'Upload Icon',
                                        'name' => 'process_item_icon_upload',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_5909a845becbc',
                                                    'operator' => '==',
                                                    'value' => 'Upload Custom Icon',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'url',
                                        'preview_size' => 'full',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array (
                                        'key' => 'field_5909a9614ddb7',
                                        'label' => 'Description',
                                        'name' => 'process_item_description',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_58e5329bb1aba',
                                                    'operator' => '==',
                                                    'value' => 'Full',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                    ),
                                ),
                            ),
                            array (
                                'key' => 'field_58e531d6b1ab2',
                                'label' => 'View More Link',
                                'name' => 'process_vlink',
                                'type' => 'link_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ecf42d1534b',
                                            'operator' => '==',
                                            'value' => 'View More LInk',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58e61021bf64c',
                        'name' => 'services',
                        'label' => 'Services',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58ecf676b4b40',
                                'label' => 'Display Option',
                                'name' => 'services_display_option',
                                'type' => 'checkbox',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Title' => 'Title',
                                    'Description' => 'Description',
                                    'View More Link' => 'View More Link',
                                ),
                                'default_value' => array (
                                ),
                                'layout' => 'horizontal',
                                'toggle' => 0,
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_58ece9e135985',
                                'label' => 'TItle',
                                'name' => 'services_heading',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ecf676b4b40',
                                            'operator' => '==',
                                            'value' => 'Title',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58ece9fa35986',
                                'label' => 'Description',
                                'name' => 'services_desc',
                                'type' => 'wysiwyg',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ecf676b4b40',
                                            'operator' => '==',
                                            'value' => 'Description',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'tabs' => 'all',
                                'toolbar' => 'full',
                                'media_upload' => 1,
                            ),
                            array (
                                'key' => 'field_5909d1e08c822',
                                'label' => 'Excerpt',
                                'name' => 'services_excerpt',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58e61021bf651',
                                'label' => 'Layout',
                                'name' => 'services_layout',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Featured (Show first 3 post)' => 'Featured (Show first 3 post)',
                                    'Full' => 'Full',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_58e61021bf652',
                                'label' => 'Services List',
                                'name' => 'services_list',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => '',
                                'max' => '',
                                'layout' => 'row',
                                'button_label' => 'Add Row',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_58e61021bf654',
                                        'label' => 'Title',
                                        'name' => 'services_title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array (
                                        'key' => 'field_58e6127e07728',
                                        'label' => 'Content',
                                        'name' => 'services_content_item',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                    ),
                                    array (
                                        'key' => 'field_58ecd8cca81fb',
                                        'label' => 'Button Link',
                                        'name' => 'services_btn_link',
                                        'type' => 'link_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                    ),
                                ),
                            ),
                            array (
                                'key' => 'field_58ece84f4ebeb',
                                'label' => 'View More Link',
                                'name' => 'services_btn_vlink',
                                'type' => 'link_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ecf676b4b40',
                                            'operator' => '==',
                                            'value' => 'View More Link',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58e53a6241477',
                        'name' => 'contact_builder',
                        'label' => 'Contact',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58e648bed5388',
                                'label' => 'Layout',
                                'name' => 'contact_layout',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Single page' => 'Single page',
                                    'Form' => 'Form',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'vertical',
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_58e53a6f41478',
                                'label' => 'Address',
                                'name' => 'contact_address',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58e648bed5388',
                                            'operator' => '==',
                                            'value' => 'Single page',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58e53a8c41479',
                                'label' => 'Phone',
                                'name' => 'contact_phone',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58e648bed5388',
                                            'operator' => '==',
                                            'value' => 'Single page',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58e53afc4147a',
                                'label' => 'Availability',
                                'name' => 'contact_availability',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58e648bed5388',
                                            'operator' => '==',
                                            'value' => 'Single page',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58e53b064147b',
                                'label' => 'Map',
                                'name' => 'contact_map',
                                'type' => 'google_map',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58e648bed5388',
                                            'operator' => '==',
                                            'value' => 'Single page',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'center_lat' => '',
                                'center_lng' => '',
                                'zoom' => '',
                                'height' => '',
                            ),
                            array (
                                'key' => 'field_58e64948d5389',
                                'label' => 'Shortcode Form',
                                'name' => 'contact_shortcode',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58e648bed5388',
                                            'operator' => '==',
                                            'value' => 'Form',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58e64967d538a',
                                'label' => 'Single Page Link',
                                'name' => 'single_page_link',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58e648bed5388',
                                            'operator' => '==',
                                            'value' => 'Form',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => '',
                                'max' => '',
                                'layout' => 'table',
                                'button_label' => 'Add Row',
                                'sub_fields' => array (
                                    array (
                                        'key' => 'field_58e64985d538b',
                                        'label' => 'Link',
                                        'name' => 'single_contact_link',
                                        'type' => 'post_object',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => array (
                                            array (
                                                array (
                                                    'field' => 'field_58e648bed5388',
                                                    'operator' => '==',
                                                    'value' => 'Form',
                                                ),
                                            ),
                                        ),
                                        'wrapper' => array (
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'post_type' => array (
                                        ),
                                        'taxonomy' => array (
                                        ),
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'return_format' => 'id',
                                        'ui' => 1,
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58e5f6c4948d6',
                        'name' => 'recent_post',
                        'label' => 'Recent Post',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58ecfd5b6cf3f',
                                'label' => 'Display Option',
                                'name' => 'display_option',
                                'type' => 'checkbox',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Title' => 'Title',
                                    'Description' => 'Description',
                                    'View More Link' => 'View More Link',
                                ),
                                'default_value' => array (
                                ),
                                'layout' => 'horizontal',
                                'toggle' => 0,
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_58e5f76c948d8',
                                'label' => 'TItle',
                                'name' => 'recent_post_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ecfd5b6cf3f',
                                            'operator' => '==',
                                            'value' => 'Title',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58e5f77b948d9',
                                'label' => 'Description',
                                'name' => 'recent_post_description',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ecfd5b6cf3f',
                                            'operator' => '==',
                                            'value' => 'Description',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => 'wpautop',
                            ),
                            array (
                                'key' => 'field_58e5f891948e0',
                                'label' => 'View More Link',
                                'name' => 'recent_vlink',
                                'type' => 'link_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58ecfd5b6cf3f',
                                            'operator' => '==',
                                            'value' => 'View More Link',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                            array (
                                'key' => 'field_58ed08cc9dac6',
                                'label' => 'Row',
                                'name' => 'recent_post_row',
                                'type' => 'checkbox',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    3 => '4',
                                    4 => '3',
                                    6 => '2',
                                ),
                                'default_value' => array (
                                ),
                                'layout' => 'horizontal',
                                'toggle' => 0,
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_58ed09449dac7',
                                'label' => 'Post Limit',
                                'name' => 'recent_post_limit',
                                'type' => 'number',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => 3,
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'min' => 3,
                                'max' => 9,
                                'step' => '',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58e617646843b',
                        'name' => 'about_builder',
                        'label' => 'Team List',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58e6189cb2870',
                                'label' => 'Layout Display',
                                'name' => '',
                                'type' => 'tab',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'placement' => 'top',
                                'endpoint' => 0,
                            ),
                            array (
                                'key' => 'field_58e618b2b2871',
                                'label' => 'Row',
                                'name' => 'about_list_row',
                                'type' => 'radio',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    3 => '4',
                                    4 => '3',
                                    6 => '2',
                                ),
                                'allow_null' => 0,
                                'other_choice' => 0,
                                'save_other_choice' => 0,
                                'default_value' => '',
                                'layout' => 'horizontal',
                                'return_format' => 'value',
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58eb47cdc57b3',
                        'name' => 'banner_featured',
                        'label' => 'Banner Featured',
                        'display' => 'row',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_58eb47fec57b7',
                                'label' => 'Display Option',
                                'name' => 'featured_display_option',
                                'type' => 'checkbox',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array (
                                    'Title' => 'Title',
                                    'Description' => 'Description',
                                    'More Link' => 'More Link',
                                    'Featured Image' => 'Featured Image',
                                ),
                                'default_value' => array (
                                ),
                                'layout' => 'horizontal',
                                'toggle' => 0,
                                'return_format' => 'value',
                            ),
                            array (
                                'key' => 'field_58eb47d5c57b4',
                                'label' => 'Title',
                                'name' => 'feaured_title',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58eb47fec57b7',
                                            'operator' => '==',
                                            'value' => 'Title',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                            array (
                                'key' => 'field_58eb47ebc57b5',
                                'label' => 'Description',
                                'name' => 'feaured_desctiption',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58eb47fec57b7',
                                            'operator' => '==',
                                            'value' => 'Description',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'maxlength' => '',
                                'rows' => '',
                                'new_lines' => 'wpautop',
                            ),
                            array (
                                'key' => 'field_58eb7057e1770',
                                'label' => 'Image',
                                'name' => 'featured_banner_image',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58eb47fec57b7',
                                            'operator' => '==',
                                            'value' => 'Featured Image',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'preview_size' => 'large',
                                'library' => 'all',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                            ),
                            array (
                                'key' => 'field_58eb4843c57bb',
                                'label' => 'Button Link',
                                'name' => 'feaured_vlink',
                                'type' => 'link_picker',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array (
                                    array (
                                        array (
                                            'field' => 'field_58eb47fec57b7',
                                            'operator' => '==',
                                            'value' => 'More Link',
                                        ),
                                    ),
                                ),
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    array (
                        'key' => '58ecd526bc8e0',
                        'name' => 'default_page_footer',
                        'label' => 'Default Page Footer',
                        'display' => 'row',
                        'sub_fields' => array (
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-custom.php',
                ),
            ),
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'default',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            0 => 'format',
        ),
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_58e624896073e',
        'title' => 'Option',
        'fields' => array (
            array (
                'key' => 'field_5922f890388f8',
                'label' => 'Header',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_58e624960c15b',
                'label' => 'Branding',
                'name' => 'branding',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'preview_size' => 'full',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array (
                'key' => 'field_5922f8b0388f9',
                'label' => 'Featured Nav Link',
                'name' => 'featured_nav_link',
                'type' => 'link_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'key' => 'field_58e6ad43a2f89',
                'label' => 'Phone Number',
                'name' => 'default_phone_number',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58e682b82788a',
                'label' => 'API',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_58e682c02788b',
                'label' => 'Google Map API',
                'name' => 'google_map_api',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'cwm-options',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_58ecc4b202b48',
        'title' => 'Page Option',
        'fields' => array (
            array (
                'key' => 'field_58ecc4bc793f4',
                'label' => 'Login Modal',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_58ecc4c8793f5',
                'label' => 'TItle',
                'name' => 'login_m_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58ecc4e9793f6',
                'label' => 'Description',
                'name' => 'login_m_description',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'wpautop',
            ),
            array (
                'key' => 'field_58ecc4f9793f7',
                'label' => 'Button Links',
                'name' => 'login_m_button_links',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '',
                'layout' => 'table',
                'button_label' => 'Add Row',
                'sub_fields' => array (
                    array (
                        'key' => 'field_58ecc515793f8',
                        'label' => 'Button Type',
                        'name' => 'login_m_btn_type',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array (
                            'Text' => 'Text',
                            'Image' => 'Image',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array (
                        'key' => 'field_58ed25fb0cd14',
                        'label' => 'Link',
                        'name' => 'login_m_btn',
                        'type' => 'link_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                    ),
                    array (
                        'key' => 'field_58ecc76683cdb',
                        'label' => 'Button Image',
                        'name' => 'login_m_btn_image',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array (
                            array (
                                array (
                                    'field' => 'field_58ecc515793f8',
                                    'operator' => '==',
                                    'value' => 'Image',
                                ),
                            ),
                        ),
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'full',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
            array (
                'key' => 'field_58ecc5b2793fa',
                'label' => 'Page widget footer',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_58eccdfdb9c71',
                'label' => 'Show all page except',
                'name' => 'show_all_page_except',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array (
                    0 => 'page',
                    1 => 'team',
                ),
                'taxonomy' => array (
                ),
                'allow_null' => 0,
                'multiple' => 1,
                'return_format' => 'object',
                'ui' => 1,
            ),
            array (
                'key' => 'field_58ecc5fb793fb',
                'label' => 'TItle',
                'name' => 'page_foot_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_58ecc64c793fc',
                'label' => 'Description',
                'name' => 'page_foot_desc',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'wpautop',
            ),
            array (
                'key' => 'field_58ed0ec6d9a28',
                'label' => 'Link',
                'name' => 'page_foot_link',
                'type' => 'link_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
            ),
            array (
                'key' => 'field_58eced80ae6e0',
                'label' => 'Blog',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_58eced8dae6e1',
                'label' => 'Blog Intro',
                'name' => 'blog_intro',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'wpautop',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-page-options',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'group_58f746bcb942a',
        'title' => 'Services process',
        'fields' => array (
            array (
                'key' => 'field_5909d4c0d36c7',
                'label' => 'Description',
                'name' => 'services_description_s',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => 'wpautop',
            ),
            array (
                'key' => 'field_58fef5e3eac27',
                'label' => 'Process',
                'name' => 'sub_process',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => '',
                'max' => '',
                'layout' => 'row',
                'button_label' => 'Add Row',
                'sub_fields' => array (
                    array (
                        'key' => 'field_58fef605eac28',
                        'label' => 'Title',
                        'name' => 'sub_process_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_5909bfab3000c',
                        'label' => 'Sub TItle',
                        'name' => 'sub_process_stitle',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_58fef649eac29',
                        'label' => 'Content',
                        'name' => 'sub_process_content',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => 'wpautop',
                    ),
                    array (
                        'key' => 'field_58fef6bdeac2b',
                        'label' => 'Icon Type',
                        'name' => 'sub_process_icon_type',
                        'type' => 'radio',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array (
                            'Default' => 'Default',
                            'Upload Icon' => 'Upload Icon',
                            'None' => 'None',
                        ),
                        'allow_null' => 0,
                        'other_choice' => 0,
                        'save_other_choice' => 0,
                        'default_value' => '',
                        'layout' => 'horizontal',
                        'return_format' => 'value',
                    ),
                    array (
                        'key' => 'field_58fef67aeac2a',
                        'label' => 'Icon',
                        'name' => 'sub_process_icon',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array (
                            array (
                                array (
                                    'field' => 'field_58fef6bdeac2b',
                                    'operator' => '==',
                                    'value' => 'Default',
                                ),
                            ),
                        ),
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array (
                            'Foundation' => 'Foundation',
                            'Arrowup' => 'Arrowup',
                            'Navigate' => 'Navigate',
                            'Activate' => 'Activate',
                            'Check' => 'Check',
                        ),
                        'default_value' => array (
                        ),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'return_format' => 'value',
                        'placeholder' => '',
                    ),
                    array (
                        'key' => 'field_58feffec29803',
                        'label' => 'Upload Image Icon',
                        'name' => 'sub_process_icon_img',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => array (
                            array (
                                array (
                                    'field' => 'field_58fef6bdeac2b',
                                    'operator' => '==',
                                    'value' => 'Upload Icon',
                                ),
                            ),
                        ),
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'full',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'service',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

endif;